apiVersion: v1
kind: Namespace
metadata:
  name: activemq-artemis-self-provisioning-plugin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-artemis-self-provisioning-plugin
  namespace: activemq-artemis-self-provisioning-plugin
  labels:
    app: activemq-artemis-self-provisioning-plugin
    app.kubernetes.io/component: activemq-artemis-self-provisioning-plugin
    app.kubernetes.io/instance: activemq-artemis-self-provisioning-plugin
    app.kubernetes.io/part-of: activemq-artemis-self-provisioning-plugin
    app.openshift.io/runtime-namespace: activemq-artemis-self-provisioning-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq-artemis-self-provisioning-plugin
  template:
    metadata:
      labels:
        app: activemq-artemis-self-provisioning-plugin
    spec:
      containers:
        - name: activemq-artemis-self-provisioning-plugin
          image: quay.io/artemiscloud/activemq-artemis-self-provisioning-plugin:dev.latest
          ports:
            - containerPort: 9443
              protocol: TCP
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          volumeMounts:
            - name: plugin-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
      volumes:
        - name: plugin-serving-cert
          secret:
            secretName: plugin-serving-cert
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: plugin-serving-cert
  name: activemq-artemis-self-provisioning-plugin
  namespace: activemq-artemis-self-provisioning-plugin
  labels:
    app: activemq-artemis-self-provisioning-plugin
    app.kubernetes.io/component: activemq-artemis-self-provisioning-plugin
    app.kubernetes.io/instance: activemq-artemis-self-provisioning-plugin
    app.kubernetes.io/part-of: activemq-artemis-self-provisioning-plugin
spec:
  ports:
    - name: 9443-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: activemq-artemis-self-provisioning-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: activemq-artemis-self-provisioning-plugin
spec:
  displayName: 'OpenShift Console ActiveMQ Artemis Self Provisioning Plugin'
  # i18n:
  #   loadType: Preload
  service:
    name: activemq-artemis-self-provisioning-plugin
    namespace: activemq-artemis-self-provisioning-plugin
    port: 9443
    basePath: '/'
